name: Run css_parser CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test ruby version matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.2', '2.3', '2.4', '2.5', '2.6', '2.7', 'jruby-head']

    steps:
      - uses: actions/checkout@v2

      - run: rm Gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake
